image: gitpod/workspace-full

tasks:
  - init: npm install && npm run build && npm install -g eslint
    command: npm run dev

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==
    - abusaidm.html-snippets@0.2.1:HrYIjYqOIABbxFB9g9kqXQ==